<a href="https://colab.research.google.com/github/DavidSenseman/BIO1173/blob/main/Class_05_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- BIO1173_CLASS_05_2:Rev 1 -->

---------------------------
**COPYRIGHT NOTICE:** This Jupyterlab Notebook is a Derivative work of [Jeff Heaton](https://github.com/jeffheaton) licensed under the Apache License, Version 2.0 (the "License"); You may not use this file except in compliance with the License. You may obtain a copy of the License at

> [http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0)

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

------------------------

# **BIO 1173: Intro Computational Biology**

## **Module 5: Natural Language Processing**

* Instructor: [David Senseman](mailto:David.Senseman@utsa.edu), [Department of Biology, Health and the Environment](https://sciences.utsa.edu/bhe/), [UTSA](https://www.utsa.edu/)

### Module 5 Material

* Part 5.1: Introduction to Hugging Face
* **Part 5.2: Hugging Face Tokenizers**
* Part 5.3: Hugging Face Datasets
* Part 5.4: Training Hugging Face Models

## Google Colab Instructions

Run next code cell to map this Colab lesson's folder /content/drive to your Google Drive. This will allow you keep a copy of your work in case you need it later.

In [ ]:
# @title **Run this cell first**
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    from google.colab import auth
    auth.authenticate_user()
    Colab = True
    print("Note: Using Google CoLab")
    !curl ipinfo.io
except:
    print("**WARNING**: Your GDrive is not mapped to /content/drive ")
    print("**WARNING**: Your work will not be saved!")
    Colab = False

You should see something _similar_ to the following output:
```text
Mounted at /content/drive
Note: Using Google CoLab
{
  "ip": "104.199.151.202",
  "hostname": "202.151.199.104.bc.googleusercontent.com",
  "city": "Taipei",
  "region": "Taiwan",
  "country": "TW",
  "loc": "25.0531,121.5264",
  "org": "AS396982 Google LLC",
  "timezone": "Asia/Taipei",
  "readme": "https://ipinfo.io/missingauth"
}

```

## YouTube Introduction to Hugging Face Tokenizers

Run the next cell to see short introduction to Hugging Face Tokenizers.

In [ ]:
from IPython.display import HTML
video_id = "VFp38yj8h3A"

HTML(f"""
<iframe width="560" height="315"
  src="https://www.youtube.com/embed/{video_id}"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
  referrerpolicy="strict-origin-when-cross-origin"> </iframe>
""")

# **Hugging Face Tokenizers**

**Hugging Face tokenizers** are essential tools in natural language processing (NLP) that convert text into numerical data, which can be processed by machine learning models. Here's a breakdown of their importance and why they are particularly valuable for computational biologists:

##### **What are Hugging Face Tokenizers?**
1. **Tokenization**: The process of breaking down text into smaller units called tokens. These tokens can be words, subwords, or characters.
2. **Normalization**: Adjusting the text to a standard format, such as lowercasing or removing punctuation.
3. **Encoding**: Converting tokens into numerical representations that models can understand.

##### **Types of Tokenizers**
1. **Word-based Tokenizers**: Split text into words. Simple but can lead to large vocabularies.
2. **Subword Tokenizers**: Break words into smaller units, balancing vocabulary size and representation. Examples include Byte Pair Encoding (BPE) and WordPiece.
3. **Character-based Tokenizers**: Split text into individual characters. Useful for languages with complex morphology.

##### **Importance for Computational Biologists**
1. **Handling Biological Texts**: Biological texts often contain specialized terminology, gene names, and sequences. Tokenizers can effectively process these texts, ensuring accurate representation and analysis.
2. **Data Preprocessing**: Tokenizers help in preparing biological data for machine learning models, enabling tasks like gene sequence analysis, protein structure prediction, and more.
3. **Efficiency**: Subword tokenizers, in particular, can handle rare and complex terms efficiently, reducing the need for extensive vocabularies and improving model performance.
4. **Integration with Models**: Hugging Face tokenizers are designed to work seamlessly with pre-trained models, allowing computational biologists to leverage state-of-the-art NLP techniques for their research.

You can find more detailed information about Hugging Face tokenizers [here](https://huggingface.co/docs/tokenizers/en/index).


## **Hugging Face Tokenizers**

Here are some of the most popular tokenizers on Hugging Face and why they are useful:

1. **Byte-Pair Encoding (BPE)**:
   - **Models**: GPT-2, RoBERTa
   - **Usefulness**: BPE tokenizers break down words into subword units, which helps in handling rare and out-of-vocabulary words efficiently. This reduces the vocabulary size while maintaining the ability to represent complex words.

2. **WordPiece**:
   - **Models**: BERT, DistilBERT
   - **Usefulness**: Similar to BPE, WordPiece tokenizers split words into subword units. They are particularly effective in handling morphological variations and rare words, making them suitable for a wide range of NLP tasks.

3. **SentencePiece**:
   - **Models**: T5, ALBERT
   - **Usefulness**: SentencePiece tokenizers can handle both word and subword tokenization. They are language-agnostic and can be trained on raw text without pre-tokenization, making them versatile for different languages and scripts.

4. **Unigram**:
   - **Models**: XLNet
   - **Usefulness**: Unigram tokenizers use a probabilistic model to generate subword units. They are effective in balancing the trade-off between vocabulary size and representation quality, making them suitable for large-scale language models.

5. **Whitespace**:
   - **Models**: Various
   - **Usefulness**: Whitespace tokenizers split text based on spaces. They are simple and fast, making them useful for tasks where precise tokenization is not critical.

These tokenizers are designed to handle different aspects of text processing, such as handling rare words, reducing vocabulary size, and maintaining the integrity of the original text. They are essential for preparing text data for machine learning models, ensuring that the input is in a format that the models can understand and process effectively.

You can find more detailed information about Hugging Face tokenizers [here](https://huggingface.co/docs/tokenizers/index).



## Log into Hugging Face

Run the next code cell to log into your Hugging Face account using your `HF_TOKEN` stored in your Colab Secrets. You may have to grant access to your Colab Secrets to run the next cell.

In [ ]:
# @title Log into Hugging Face.

from google.colab import userdata
from huggingface_hub import login

# Get the token from Colab Secrets and log in
try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    login(token=HF_TOKEN)
    print("Successfully logged into Hugging Face! ✅")
except Exception as e:
    print(f"Error logging into Hugging Face: {e} ❌")

If your `HF_Token` is correctly stored in your Colab Secrets, you should see the following output:

```text
Successfully logged into Hugging Face! ✅
```
Information on how to obtain your `HF_TOKEN` and store it in your Colab Secrets has already been provided to you. If you are having trouble getting it to work, please see the course Instructor or a TA.

## Install Transformers

Run the code in the next cell to install Hugging Face transformers in your Colab environment. This will take a while.

In [ ]:
# @title Install Transformers

!pip install -q transformers
!pip install -q transformers[sentencepiece]

print("Hugging Face transformers were sucessfully installed. ✅  ")

If the code is correct, you should see the following output:
```text
Hugging Face transformers were sucessfully installed. ✅  
```

## Example 1 - Step 1: Create Tokenizer

In Step 1, we create a Hugging Face tokenizer using the `distilbert-base-uncased` as our tokenizer model. It is important to remember that the `distilbert-base-uncased` tokenizer is a **WordPiece** tokenizer. WordPiece tokenizers split words into subword units. They are particularly effective in handling morphological variations and rare words, making them suitable for a wide range of NLP tasks.

In **Exercise 1** we will shift to a **SentencePiece** tokenizer to see how these two tokenizer types differ.

In [ ]:
# @title Example 1 - Step 1: Create Tokenizer

import os
from google.colab import userdata

# Print warning
print("Creating tokens. This will take a while....")

os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')

# Import AFTER setting the env var
from transformers import AutoTokenizer

eg_model = "distilbert-base-uncased"
eg_tokenizer = AutoTokenizer.from_pretrained(eg_model)

If the code is correct, you should see the following output.

```text
Creating tokens. This will take a while...
```

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_2_image01F.png)

### Example 1 - Step 2: Tokenize a Sentence

The code in the cell below shows how to tokenize a sentence. For this example, we will use a quotation from Geoffrey Hinton, a pioneer in the field of deep learning:
> "To make a real impact on AI, we need to build systems that can learn from very large amounts of data."
>
This quote emphasizes the importance of data-driven learning in the development and advancement of neural networks and artificial intelligence

In [ ]:
# @title Example 1 - Step 2: Tokenize a sentence

# Create sentence variable
eg_sentence_1 = "To make a real impact on AI, we need to build systems that can learn from very large amounts of data."

# Tokenize sentence
eg_encoded = eg_tokenizer(eg_sentence_1)

# Print result
print(eg_encoded)


If the code is correct your should see the following output

```text
{'input_ids': [101, 2000, 2191, 1037, 2613, 4254, 2006, 9932, 1010, 2057, 2342, 2000, 3857, 3001, 2008, 2064, 4553, 2013, 2200, 2312, 8310, 1997, 2951, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

```

The result of this tokenization contains two elements:

* **input_ids:** The individual subword indexes, each index uniquely identifies a subword.

* **attention_mask:**  Which values in input_ids are meaningful and not padding. This sentence had no padding, so all elements have an attention mask of "1". Later, we will request the output to be of a fixed length, introducing padding, which always has an attention mask of "0". Though each tokenizer can be implemented differently, the attention mask of a tokenizer is generally either "0" or "1".

Due to subwords and special tokens, the number of tokens may not match the number of words in the source string. We can see the meanings of the individual tokens by converting these IDs back to strings.


### Example 1 - Step 3: Show Meaning of Tokens

The code in the cell below shows the meaning of the tokens.

In [ ]:
# Example 2 - Step 3: Show meaning of tokens

# Show meaning
eg_tokenizer.convert_ids_to_tokens(eg_encoded.input_ids)

If the code is correct your should see the following output
```text
['[CLS]',
 'to',
 'make',
 'a',
 'real',
 'impact',
 'on',
 'ai',
 ',',
 'we',
 'need',
 'to',
 'build',
 'systems',
 'that',
 'can',
 'learn',
 'from',
 'very',
 'large',
 'amounts',
 'of',
 'data',
 '.',
 '[SEP]']
 ```


The sentence was broken down into tokens, which include special tokens **[CLS]** and **[SEP]**:

**[CLS]:** This token is added at the beginning of the sequence. It stands for "classification" and is used in tasks like sentence classification.

**Tokens:** The words and punctuation marks from your sentence have been split into individual tokens.

**[SEP]:** This token is added at the end of the sequence to indicate the end of the input. It stands for "separator" and is used in tasks involving multiple sequences.

The tokenization process is essential for preparing text data for model processing. It ensures that the text is transformed into a format that the model can understand and work with.

### Example 1 - Step 4: Convert IDS to Tokens

The cell below shows the code to convert the IDS from Example 1 - Step 3 to tokens.

In [ ]:
# @title Example 1 - Step 4: Convert IDS to Tokens

# Convert ids back into tokens
eg_tokenizer.convert_ids_to_tokens([0, 100, 101, 102, 103])

If the code is correct your should see the following output

```text
['[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]']
```


## Explanation of Special Tokens in Tokenizer Output

The output `['[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]']` consists of special tokens commonly used by tokenizers in the Hugging Face library:

1. **[PAD]**: Padding token used to pad sequences to ensure they are of the same length.
2. **[UNK]**: Unknown token used to represent tokens that are not found in the tokenizer's vocabulary.
3. **[CLS]**: Classification token added at the beginning of the sequence, often used for tasks like sentence classification.
4. **[SEP]**: Separator token used to indicate the end of a sequence or to separate multiple sequences.
5. **[MASK]**: Mask token used in masked language modeling tasks, where certain tokens are masked and the model attempts to predict them.

These special tokens are integral to various NLP tasks, such as sequence classification, question answering, and language modeling. They help the model understand and process input data in a structured way.

-----------------------------

## **Comparison of DistilBERT and ALBERT Tokenizers**

For **Exercise 1** we will be comparing the `DistilBERT` tokenizer with the `ALBERT` tokenizer. Here are some of the differences we should expect to see:

#### Tokenization Method
- **DistilBERT**: Utilizes the WordPiece tokenization method. This method breaks down words into subword units and uses the `##` prefix to denote subwords that appear within a word.
- **ALBERT**: Uses the SentencePiece tokenization method. SentencePiece tokenizers break down text into subword units and use the underscore (`▁`) character to indicate spaces before words.

#### Special Tokens
- **DistilBERT**: Uses special tokens such as `[CLS]` (classification token added at the beginning of the sequence) and `[SEP]` (separator token used to indicate the end of a sequence or to separate multiple sequences).
- **ALBERT**: Also uses special tokens like `[CLS]` and `[SEP]`. However, the representation and tokenization of the text might differ due to the SentencePiece method.

#### Vocabulary
- **DistilBERT**: Has a distinct vocabulary file based on the WordPiece tokenization method, which includes tokens with the `##` prefix to denote subwords.
- **ALBERT**: Has a different vocabulary file based on the SentencePiece tokenization method, which includes tokens with the underscore (`▁`) character to denote spaces before words.

---------------------------

## **Exercise 1 - Step 1: Create Tokenizer**

In the cell below, create a Hugging Face tokenizer using the `albert-large-v2` as your tokenizer model. Call your model `ex_model` and your tokenizer `ex_tokenizer`.

**CODE HINTS:**

Change the prefix `eg_` to `ex_`.

In [ ]:
# @title **Exercise 1 - Step 1: Create Tokenizer**



If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_2_image02G.png)

## **Exercise 1 - Step 2: Tokenize a Sentence**

In the cell below use the following sentence to create `ex_sentence_1`:

"Hugging Face is on a mission to democratize artificial intelligence through open source and open science, making state-of-the-art models accessible to everyone."

Use your `ex_tokenizer` to tokenize the sentence to create `ex_encoded`. Then print out the result of the tokenization, `ex_encoded`.

**CODE HINTS:**

Change the prefix `eg_` to `ex_`.

In [ ]:
# @title Exercise 1 - Step 2: Tokenize a Sentence





If the code is correct you should see the following output:

```text
{'input_ids': [2, 20676, 276, 25, 27, 21, 1408, 20, 6456, 2952, 6809, 2872, 120, 368, 1267, 17, 368, 762, 15, 544, 146, 8, 1041, 8, 124, 8, 2900, 2761, 7342, 20, 1266, 9, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

```

with additional numbers at the right.

## **Exercise 1 - Step 3: Show Meaning of Tokens**

In the cell below, write the code to use your `ex_tokenizer` to show the meanings of the tokens in `ex_encoded`.



In [ ]:
# @title Exercise 1 - Step 3: Show Meaning of Tokens



If the code is correct you should see the following output:
```text
['[CLS]',
 '▁hugging',
 '▁face',
 '▁is',
 '▁on',
 '▁a',
 '▁mission',
 '▁to',
 '▁democrat',
 'ize',
 '▁artificial',
 '▁intelligence',
 '▁through',
 '▁open',
 '▁source',
 '▁and',
 '▁open',
 '▁science',
 ',',
 '▁making',
 '▁state',
 '-',
 'of',
 '-',
 'the',
 '-',
 'art',
 '▁models',
 '▁accessible',
 '▁to',
 '▁everyone',
 '.',
 '[SEP]']
 ```

## Explanation of Tokenization Output

The output you're seeing is the result of tokenization using the `ALBERT` tokenizer. Here's what each part of the output means:

1. **[CLS]**: This special token is added at the beginning of the sequence. It stands for "classification" and is often used in tasks like sentence classification or as a marker for the start of the sequence.

2. **▁ (underscore character)**: This symbol is used in SentencePiece tokenization to indicate a space before a word. It's a way to handle whitespace in the text.

3. **Tokens**: The words and subwords in your input sentence have been split into tokens. For example:
   - `'▁hugging'` represents the word "hugging" with a preceding space.
   - `'▁face'` represents the word "face" with a preceding space.
   - `'▁is'`, `'▁on'`, `'▁a'`, etc., represent individual words with preceding spaces.
   - `'▁democrat'`, `'ize'` represent the word "democratize," split into two subwords.

4. **Punctuation**: Punctuation marks like commas and periods are kept as separate tokens.

5. **[SEP]**: This special token is added at the end of the sequence to indicate the end of the input. It stands for "separator" and is used in tasks involving multiple sequences.

#### **Simplified Explanation of the Tokenization Process**
- The tokenizer breaks down the sentence into smaller units called tokens.
- Special tokens `[CLS]` and `[SEP]` are added to mark the beginning and end of the sequence.
- Each word and punctuation mark is converted into a token, with subword tokenization applied to handle complex or rare words.

Tokenization is crucial for transforming text into a format that machine learning models can process. It ensures that the input is properly segmented and encoded into numerical representations.

--------------------

## **Exercise 1 - Step 4: Convert IDS to Tokens**

In the cell below write the code to convert the IDS in your `ex_tokenizer` back into tokens.

In [ ]:
# @title Exercise 1 - Step 4: Convert IDS to Tokens



If the code is correct you should see the following output:

```text
['<pad>', '▁if', '▁like', 'ly', 'n']
```

## Explanation of Tokenizer Output

The command `tokenizer.convert_ids_to_tokens([0, 100, 101, 102, 103])` converts a list of token IDs back into their corresponding tokens using the tokenizer's vocabulary. Here's what each part of the output means:

1. **`<pad>`**: This token corresponds to the ID `0` and is typically used for padding sequences to a uniform length.
2. **▁if**: The token with ID `100`, indicating the word "if" with a preceding space. The underscore (`▁`) denotes a space before the word, as seen in SentencePiece tokenization.
3. **▁like**: The token with ID `101`, representing the word "like" with a preceding space.
4. **ly**: The token with ID `102`, representing the subword "ly" which might be a part of a larger word.
5. **n**: The token with ID `103`, representing the letter "n", which might be part of a subword or a standalone token depending on the context.

These token IDs are mapped to their corresponding tokens based on the tokenizer's vocabulary. The presence of subword tokens like "ly" and "n" indicates that the tokenizer uses a subword-based method (e.g., SentencePiece, WordPiece) to handle the text.


-----------------------------------

## **Difference in Tokenization Output: ALBERT vs. DistilBERT**

The difference in output between the ALBERT tokenizer used in **Exercise 1** and the DistilBERT tokenizer used in Example 1 is due to the distinct tokenization methods used by each model. Here are the key differences:

#### Tokenization Method
- **ALBERT**: Uses SentencePiece tokenization, which breaks down text into subword units and adds the underscore (`▁`) character to indicate spaces. This helps handle complex words and out-of-vocabulary terms efficiently.
- **DistilBERT**: Uses WordPiece tokenization, which also breaks down text into subword units but does not use the underscore character. Instead, it adds `##` before subword tokens that are not at the start of a word.

#### Special Tokens
- Both ALBERT and DistilBERT add `[CLS]` at the beginning and `[SEP]` at the end of the sequence, but their internal tokenization processes differ due to the tokenization method used.

#### Vocabulary
- The vocabulary files used by ALBERT and DistilBERT are different. Each tokenizer has its unique vocabulary that influences how text is broken down into tokens.

----------------------------------

# **Tokenizing a List of Sequences**

**Tokenizing a list of sequences** is a crucial step in preparing data for machine learning models, especially in the field of natural language processing (NLP) and bioinformatics. Here's why tokenization is important and why it might be of interest to a computational biologist:

#### **Importance of Tokenizing a List of Sequences**

1. **Uniform Data Representation**: Tokenization transforms sequences (e.g., text, DNA/RNA sequences) into numerical representations that models can process. This ensures that all sequences are uniformly represented, making it easier to feed them into machine learning algorithms.

2. **Handling Variable-Length Sequences**: Biological data, such as gene sequences, can vary in length. Tokenization, combined with techniques like padding and truncation, ensures that all sequences are of a uniform length, which is necessary for batch processing.

3. **Capturing Contextual Information**: Advanced tokenizers, such as those used in NLP models, can capture contextual information by breaking down sequences into meaningful subunits (e.g., words, subwords, amino acids). This helps models understand the relationships and patterns within the sequences.

4. **Reducing Vocabulary Size**: Subword tokenizers (e.g., SentencePiece, WordPiece) break down rare and complex terms into smaller, more manageable units. This reduces the overall vocabulary size, making the model more efficient and capable of handling out-of-vocabulary terms.

5. **Facilitating Transfer Learning**: Pre-trained models, such as BERT or ALBERT, often come with their own tokenizers. By tokenizing sequences in a manner consistent with these models, researchers can leverage transfer learning, applying pre-trained models to their specific tasks with minimal retraining.

#### **Why Tokenization is of Interest to Computational Biologists**

1. **Gene Sequence Analysis**: Tokenizing DNA/RNA sequences allows computational biologists to apply machine learning models to tasks such as gene prediction, sequence alignment, and motif discovery.

2. **Protein Structure Prediction**: Tokenizing amino acid sequences helps in predicting protein structures, functions, and interactions. This can lead to advancements in drug discovery and understanding of biological processes.

3. **Text Mining in Biological Literature**: Tokenizing scientific texts and literature enables computational biologists to perform text mining, extracting valuable information, identifying trends, and gaining insights from large volumes of published research.

4. **Data Preprocessing**: Proper tokenization is a key step in data preprocessing, ensuring that biological data is in a suitable format for downstream analysis. This includes normalization, handling missing data, and preparing input for various bioinformatics tools.

5. **Integration with NLP Models**: Tokenizing biological sequences or texts allows computational biologists to integrate their data with NLP models, enabling tasks such as entity recognition, relationship extraction, and knowledge discovery.

In summary, **tokenization is a vital step** in transforming biological sequences into a format that can be effectively processed by machine learning models. It enhances the efficiency, accuracy, and interpretability of computational biology tasks, leading to more meaningful insights and discoveries.



## Example 2 - Step 1: Entity Tagging

The code in the cell below creates a variable, `eg_sequences` with the three DNA sequences. The top two sequences are labelled `ORF` while the bottom sequence is labelled as not an `ORF`.

In molecular genetics, `ORF` stands for **Open Reading Frame**. An open reading frame is a continuous stretch of nucleotides in a DNA (or RNA) sequence that has the potential to be translated into a protein. It starts with a start codon (usually AUG, which codes for methionine) and ends with a stop codon (such as UAA, UAG, or UGA).

ORFs are important because they help scientists identify protein-coding regions within a genome. In gene prediction and annotation, finding ORFs is a key step in determining which parts of the DNA sequence may encode functional proteins.

The code in the cell below tokenises a batch of DNA sequences with a BERT tokenizer, padding them to the longest sequence, adding special `[CLS]`/`[SEP]` tokens, and returning PyTorch tensors. It then prints the resulting `input_ids` (integer token IDs) and `attention_mask` (1s for real tokens, 0s for padding), preparing the data for input into a BERT‑style model for downstream tasks such as ORF prediction.

In [ ]:
# @title Example 2 - Step 1: Entity Tagging

from transformers import BertModel, BertTokenizer
import torch

# Define DNA sequences
eg_sequences = [
    "ATGCGTACCGATGCTTACGTTAGCATCGTATCGTAGCTGA", # ORF
    "ATGACCGTAACTGCTGCCATCGTATGCAGTCTGATGCTAA", # ORF
    "ACTGTCGACCAGTCTAGCATCGGTTACGATCGTACAGTAC"  # Not ORF
]

# Encode Sequences
eg_encoded = eg_tokenizer(eg_sequences, padding=True, add_special_tokens=True,
                       return_tensors="pt")  # Ensure outputs are tensors

print("Input IDs")
for a in eg_encoded.input_ids:
    print(a)

print("**Attention Mask**")
for a in eg_encoded.attention_mask:
    print(a)

If the code is correct you should see the following output:
```text
Input IDs
tensor([  101,  2012, 18195, 13512,  6305,  2278, 20697, 18195,  5946,  2278,
        13512, 15900, 11266,  2278, 13512,  4017,  2278, 13512,  8490,  6593,
         3654,   102,     0])
tensor([  101,  2012,  3654,  9468, 13512, 11057,  6593, 18195,  2102, 18195,
        11266,  2278, 13512,  4017, 18195,  8490, 13535,  2102, 20697, 18195,
         2696,  2050,   102])
tensor([  101,  2552, 13512,  2278,  3654, 16665, 13512, 25572, 18195,  4017,
         2278, 13871,  5946,  2278, 20697,  2278, 13512, 19629, 13512,  6305,
          102,     0,     0])
**Attention Mask**
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])
```

The input_ids tensors represent the tokenized and encoded version of your input sequences. Each tensor corresponds to a sequence, with special tokens and padding added as needed. Let's look at the first tensor:

First Sequence:

~~~text
tensor([  101,  2012, 18195, 13512,  6305,  2278, 20697, 18195,  5946,  2278,
         13512, 15900, 11266,  2278, 13512,  4017,  2278, 13512,  8490,  6593,
           102,     0,     0])

~~~

* `101` represents the `[CLS]` token added at the beginning of the sequence.
* The numbers like `2012`, `18195`, `13512`, ... represent the token IDs for the characters in your sequence.
* `102` represents the `[SEP]` token added at the end of the sequence.
* `0` represents the `[PAD]` tokens added to pad the sequence to a uniform length.

### Attention Mask

The attention_mask tensors indicate which tokens should be attended to (1) and which tokens are just padding (0). This helps the model to focus on the relevant tokens and ignore the padding tokens.

First Sequence:

~~~text
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

~~~
All relevant tokens (including special tokens) have a value of `1`. The padding tokens have a value of `0`.

#### **Summary**
* **Input IDs:** These tensors contain the token `IDs` for the sequences, including special tokens `[CLS]` and `[SEP]`, and padding tokens `[PAD]` to ensure uniform length.

* **Attention Mask:** These tensors indicate which tokens should be attended to by the model and which tokens are padding.

This output ensures that the sequences are properly formatted for processing by the model, with attention focused on the relevant tokens.


## Example 2 - Step 2: Analyze Tokens with Neural Network

The code in the cell below loads a pretrained `bert-base-uncased` tokenizer (`eg_tokenizer`)and model (`eg_model`), tokenises a batch of sequences (`eg_sequnces`) and `attention_mask`), runs a forward pass without gradient computation to obtain the last hidden states, extracts the hidden state of the `[CLS]` token from the first position of each sequence, and prints these `[CLS]` representations as vectors which can be used for downstream classification tasks--in this case identifying `ORFs`.


In [ ]:
# @title Example 2 - Step 2: Analyze Tokens with Neural Network

from transformers import BertModel, BertTokenizer
import torch

# Define model and tokenizer
eg_model_name = "bert-base-uncased"
eg_tokenizer = BertTokenizer.from_pretrained(eg_model_name)
eg_model = BertModel.from_pretrained(eg_model_name)

# Prepare inputs
input_ids = eg_encoded["input_ids"]
attention_mask = eg_encoded["attention_mask"]

# Perform forward pass through the model
with torch.no_grad():
    eg_outputs = eg_model(input_ids=input_ids, attention_mask=attention_mask)

# Extract hidden states (last layer)
eg_hidden_states = eg_outputs.last_hidden_state

# Use hidden states for classification
eg_cls_token_hidden_state = eg_hidden_states[:, 0, :]  # Select [CLS] token hidden state
print(eg_cls_token_hidden_state)


If the code is correct you should see the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_2_image03G.png)
```text
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
tensor([[-0.6225,  0.0124,  0.0010,  ...,  0.0586, -0.1268,  0.6282],
        [-0.8602,  0.0782, -0.0059,  ...,  0.1884,  0.1436,  0.5705],
        [-0.5524,  0.0369,  0.0565,  ...,  0.0031, -0.0707,  0.7200]])
```
You should focus on the tensor values:

```text
tensor([[-0.6225,  0.0124,  0.0010,  ...,  0.0586, -0.1268,  0.6282],
        [-0.8602,  0.0782, -0.0059,  ...,  0.1884,  0.1436,  0.5705],
        [-0.5524,  0.0369,  0.0565,  ...,  0.0031, -0.0707,  0.7200]])
```
These tensor values will be used in the next step to predict whether or not a particular DNA sequence is a `ORF`.

## Example 2 - Step 3:  Use Tensors to Make Predictions

The code in the cell below uses the tensors generated in the previous step to make predictions whether a DNA sequence is a `OFR`.

In [ ]:
# @title Example 2 - Step 3:  Use Tensors to Make Predictions

import torch
from sklearn.linear_model import LogisticRegression

# Y labels
Y_labels = torch.tensor([1, 1, 0])

# Convert to numpy arrays
X = eg_cls_token_hidden_state.numpy()
y = Y_labels.numpy()

# Train a logistic regression classifier
eg_clf = LogisticRegression()
eg_clf.fit(X, y)

# Print header
print("ORF Predictions: 1=True, 0=False")

# Make predictions
eg_predictions = eg_clf.predict(X)
print(eg_predictions)


If the code is correct you should see the following output:
```text
ORF Predictions: 1=True, 0=False
[1 1 0]
```

The predicted labels [1, 1, 0] indicate how the logistic regression classifier has categorized each of the input sequences based on the hidden states from the BERT model.

Specifically:

* The first sequence is predicted to belong to class 1 (ORF).
* The second sequence is predicted to belong to class 1 (ORF).
* The third sequence is predicted to belong to class 0 (Not ORF).

### Example Scenario

Imagine you're working on classifying gene sequences into different functional groups based on their sequence patterns. The predicted labels [0, 1, 0] might represent different functional groups, such as:

* Class 0: Non-coding sequences (Not ORF).
* Class 1: Protein-coding sequences (ORF).

In this scenario, the model has correctly identified the first and second sequences as protein-coding sequences (class 1), while the third sequences was a non-coding sequences (class 0).

The output demonstrates the practical application of deep learning models in sequence classification and showcases the potential of transformer-based models in extracting meaningful features from complex biological data.

The output `[0, 1, 0]` represents the predicted class labels for each of the input sequences. Here's the interpretation:

1. **First Sequence:** The predicted label is 0.

2. **Second Sequence:** The predicted label is 1.

3. **Third Sequence:** The predicted label is 0.

This means that, according to the logistic regression classifier trained on the hidden states of the `[CLS]` token:

* The first sequence belongs to class 0.

* The second sequence belongs to class 1.

* The third sequence belongs to class 0.

These class labels are based on the training data provided (in this case, the labels tensor) and the features extracted from the hidden states of the input sequences. You can use these predicted labels for various downstream tasks, such as categorizing the sequences into different classes or groups.

## **Exercise 2 - Step 1: Entity Tagging**

In the cell below creates a variable, `ex_sequences` with the following three DNA sequences:

```type
"TATAAAAGGCGTACGTAGCTAGCTAG",  # Promotor sequence
"CGTAGCTAGCTAGCGCGCGCGCGCGC",  # Not promotor sequence
"GCGCGTATATAAGCTAGCTAGCTAGC"   # Promotor sequence
```
The top and bottom sequences are labelled `Promotor sequence` while the middle sequence is labelled `Not promotor sequence`.

A **promoter sequence** is a region of DNA located upstream (before) the start of a gene that plays a crucial role in initiating transcription—the process by which RNA is synthesized from a DNA template.

**Key Features of Promoter Sequences:**
* Binding Site for RNA Polymerase: Promoters contain specific motifs where RNA polymerase and transcription factors bind to begin transcription.
* TATA Box: A common motif in eukaryotic promoters, typically found about 25–35 bases upstream of the transcription start site. It has the sequence TATAAA and helps position RNA polymerase correctly.
* Regulatory Elements: Promoters may also include other elements like enhancers or silencers that influence the rate of transcription.

In the cell below tokenise your `ex_sequences` with a BERT tokenizer, padding them to the longest sequence, adding special `[CLS]`/`[SEP]` tokens, and returning PyTorch tensors. Then print out the resulting `input_ids` (integer token IDs) and `attention_mask`.

In [ ]:
# @title Exercise 2 - Step 1: Entity Tagging



If the code is correct you should see the following output:
```text
Input IDs
tensor([  101, 23236, 11057,  8490, 18195, 13512,  6305, 13512,  8490, 25572,
        18195, 15900,   102,     0,     0])
tensor([  101,  1039, 13512,  8490, 25572, 18195, 15900,  2278, 18195, 18195,
        18195, 18195, 18195, 18195,   102])
tensor([  101,  1043,  2278, 18195, 13512,  6790,  2696,  8490, 25572, 18195,
        15900, 25572, 18195,   102,     0])
**Attention Mask**
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])
```

## **Exercise 2 - Step 2: Entity Tagging**

In the cell below write the code to load the pretrained `bert-base-uncased` tokenizer as `ex_tokenizer` along with a model called `ex_model` and tokenize your DNA sequences as `ex_sequences`. Print out the Inout IDs along with the Attention mask.

In [ ]:
# @title Exercise 2 - Step 2: Entity Tagging




If the code is correct you should see the following output:
![___](https://biologicslab.co/BIO1173/images/class_05/class_05_2_image01A.png)
```text
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
tensor([[-0.5264,  0.2110, -0.0475,  ..., -0.0566, -0.0026,  0.5632],
        [-0.9368,  0.3725, -0.0691,  ...,  0.0979,  0.1384,  0.4099],
        [-0.6620,  0.1959,  0.0234,  ..., -0.0666, -0.1439,  0.7795]])

```

## **Exercise 2 - Step 3:  Use Tensors to Make Predictions**

In the cell below use the tensors generated in the previous step to make predictions whether a DNA sequence is a `Promotor Sequence`.

You will need to change your `Y` labels to the following:
```text
# Y labels
Y_labels = torch.tensor([1, 0, 1])
```

In [ ]:
# @title Exercise 2 - Step 3:  Use Tensors to Make Predictions



If the code is correct you should see the following output:

```text
ORF Predictions: 1=True, 0=False
[1 0 1]
```
The predicted labels [1, 0, 1] indicate how the logistic regression classifier has categorized each of the input sequences based on the hidden states from the BERT model.

Specifically:

* The first sequence is predicted to belong to class 1 (ORF).
* The second sequence is predicted to belong to class 0 (Not ORF).
* The third sequence is predicted to belong to class 1 (ORF).

## Example 3: Medical Use Case

Example 3 will provide a **medical use case** for using a pretrained `bert-base-uncased` tokenizer and model to analyze 3 different types of clinical notes: cardiovascular, respiratory and neurological.

In [ ]:
# @title Example 3: Medical Use Case

from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from transformers import BertModel, BertTokenizer
import torch


# Define maximum length
MAX_LEN=512

# Step 1: Define patient repots-----------------------------------------
eg_patient_reports = [
    "Patient presents with chest pain radiating to left arm, shortness of breath, and elevated troponin levels.",  # Cardiovascular
    "Patient reports persistent cough for 3 weeks, wheezing on auscultation, history of smoking 20 pack-years.",  # Respiratory
    "Patient exhibits sudden onset confusion, right-sided weakness, slurred speech, CT shows ischemic changes.",  # Neurological
    "Chest x-ray shows cardiomegaly, patient has bilateral leg edema and orthopnea.",  # Cardiovascular
    "Spirometry reveals FEV1/FVC ratio of 0.65, consistent with obstructive pattern.",  # Respiratory
]

# Labels: 0=Cardiovascular, 1=Respiratory, 2=Neurological
Y_labels = torch.tensor([0, 1, 2, 0, 1])

# Define model and tokenizer (consider using BioBERT or ClinicalBERT for better results)
eg_model_name = "bert-base-uncased"  # Or "dmis-lab/biobert-v1.1" for medical text
tokenizer = BertTokenizer.from_pretrained(eg_model_name)
eg_model = BertModel.from_pretrained(eg_model_name)

# Encode clinical notes
eg_encoded = tokenizer(eg_patient_reports, padding=True, truncation=True,
                    max_length=MAX_LEN, add_special_tokens=True, return_tensors="pt")

print("Sample Input IDs (first note):")
print(eg_encoded.input_ids[0][:20])  # Show first 20 tokens

# Step 2: Extract embeddings--------------------------------------------

# Perform forward pass
with torch.no_grad():
    outputs = eg_model(input_ids=eg_encoded["input_ids"],
                    attention_mask=eg_encoded["attention_mask"])

# Extract [CLS] token embeddings for classification
cls_embeddings = outputs.last_hidden_state[:, 0, :]
print(f"Embedding shape: {cls_embeddings.shape}")

# Step 3: Train classifier and predict-----------------------------------

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

# Convert to numpy
X = cls_embeddings.numpy()
y = Y_labels.numpy()

# Train classifier
clf = LogisticRegression(max_iter=1000)
clf.fit(X, y)

# Make predictions
predictions = clf.predict(X)
probabilities = clf.predict_proba(X)[:, 1]

# Display results
categories = ["Cardiovascular", "Respiratory", "Neurological"]
print("\n--- Diagnosis Category Predictions ---")
for i, (note, pred, actual) in enumerate(zip(eg_patient_reports, predictions, y)):
    print(f"\nNote {i+1}: {note[:60]}...")
    print(f"  Predicted: {categories[pred]} | Actual: {categories[actual]}")


If the code is correct, you should see the following output:
![___](https://biologicslab.co/BIO1173/images/class_05/class_05_2_image01A.png)
```text
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Sample Input IDs (first note):
tensor([  101,  5776,  7534,  2007,  3108,  3255, 23229,  2000,  2187,  2849,
         1010,  2460,  2791,  1997,  3052,  1010,  1998,  8319, 19817,  7361])
Embedding shape: torch.Size([5, 768])

--- Diagnosis Category Predictions ---

Note 1: Patient presents with chest pain radiating to left arm, shor...
  Predicted: Cardiovascular | Actual: Cardiovascular

Note 2: Patient reports persistent cough for 3 weeks, wheezing on au...
  Predicted: Respiratory | Actual: Respiratory

Note 3: Patient exhibits sudden onset confusion, right-sided weaknes...
  Predicted: Neurological | Actual: Neurological

Note 4: Chest x-ray shows cardiomegaly, patient has bilateral leg ed...
  Predicted: Cardiovascular | Actual: Cardiovascular

Note 5: Spirometry reveals FEV1/FVC ratio of 0.65, consistent with o...
  Predicted: Respiratory | Actual: Respiratory
```

The code in Example 3 demonstrates a basic text classification pipeline for medical text. It processes five clinical notes, extracts semantic features from the text using a pre-trained Transformer model (specifically BERT), and trains a simple machine learning classifier (Logistic Regression) to categorize them based on specific medical conditions.

## Output Explanation

**Input Encoding:**

The tokenizer converts the raw text into numerical IDs that the model can understand.
The output shows the first 20 tokens of the first clinical note (e.g., [CLS] for the start, [PAD] for padding, and specific words like "Patient", "presents", "with").

**Embedding Extraction:**

The model processes the text and outputs a 3D tensor of shape [5, 768]. This means:
5: There are 5 notes in the input.
768: Each note is represented by a 768-dimensional vector.

**Classification Results:**

The **LogisticRegression model** successfully classified all 5 clinical notes.

* Note 1 & 4 (Cardiovascular): Correctly identified chest pain and cardiomegaly as cardiovascular issues.
* Note 2 & 5 (Respiratory): Correctly identified cough, wheezing, and spirometry results as respiratory issues.
* Note 3 (Neurological): Correctly identified confusion and weakness as neurological issues.

## **Exercise 3: Medical Use Case**

For **Exercise 3**, write the code to use a pretrained `bert-base-uncased` tokenizer and model to analyze 3 different types of clinical notes (i.e., cardiovascular, respiratory, neurological).

**Code Hints:**

1. Change the maximum length to 255
```python
# Define maximum length
MAX_LEN=256
```

2. Use this code snippet for your Patient reports:
```python
# Step 1: Define patient reports -----------------------------------------
ex_patient_reports = [
    "Started taking metformin last week, now experiencing severe nausea and diarrhea daily.",  # ADR
    "My blood pressure medication is working great, feeling much better.",  # No ADR
    "After the antibiotic course, developed a widespread itchy rash all over my body.",  # ADR
    "Taking my vitamins every morning as prescribed, no issues at all.",  # No ADR
    "Since starting the new antidepressant, having terrible insomnia and heart palpitations.",  # ADR
    "Cholesterol medication keeping my levels in check, doctor is pleased.",  # No ADR
]
```

3. Change the Y labels to match the patient reports:
```python
# Labels: 1=ADR present, 0=No ADR
Y_labels = torch.tensor([1, 0, 1, 0, 1, 0])
```

4. Change the `Display results` section to the following:
```python
# Display results
print("\n--- Adverse Drug Reaction Detection ---")
print("=" * 60)
for i, (report, pred, prob, actual) in enumerate(zip(patient_reports, predictions, probabilities, y)):
    status = "⚠️  ADR DETECTED" if pred == 1 else "✓  No ADR"
    print(f"\nReport {i+1}: \"{report[:50]}...\"")
    print(f"  {status} (Confidence: {prob:.2%}) | Actual: {'ADR' if actual else 'No ADR'}")

print("\n" + "=" * 60)
print("Classification Report:")
print(classification_report(y, predictions, target_names=["No ADR", "ADR Present"]))
```
5. Change the prefix `eg_` to `ex_`.

In [ ]:
# @title Exercise 3: Medical Use Case



If the code is correct, you should see something _similar_ to the following output:
![___](https://biologicslab.co/BIO1173/images/class_05/class_05_2_image01A.png)

```text
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Sample Input IDs (first note):
tensor([  101,  2318,  2635,  2777, 14192,  2378,  2197,  2733,  1010,  2085,
        13417,  5729, 19029,  1998, 22939, 12171, 20192,  3679,  1012,   102])
Embedding shape: torch.Size([6, 768])

--- Adverse Drug Reaction Detection ---
============================================================

Report 1: "Started taking metformin last week, now experienci..."
  ⚠️  ADR DETECTED (Confidence: 96.09%) | Actual: ADR

Report 2: "My blood pressure medication is working great, fee..."
  ✓  No ADR (Confidence: 5.83%) | Actual: No ADR

Report 3: "After the antibiotic course, developed a widesprea..."
  ⚠️  ADR DETECTED (Confidence: 93.37%) | Actual: ADR

Report 4: "Taking my vitamins every morning as prescribed, no..."
  ✓  No ADR (Confidence: 6.37%) | Actual: No ADR

Report 5: "Since starting the new antidepressant, having terr..."
  ⚠️  ADR DETECTED (Confidence: 93.57%) | Actual: ADR

Report 6: "Cholesterol medication keeping my levels in check,..."
  ✓  No ADR (Confidence: 4.77%) | Actual: No ADR

============================================================
Classification Report:
              precision    recall  f1-score   support

      No ADR       1.00      1.00      1.00         3
 ADR Present       1.00      1.00      1.00         3

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6

```

The code in **Exercise 3** demonstrates a binary text classification task to detect Adverse Drug Reactions (ADRs). It leverages a pre-trained transformer model (BERT) to understand the context of patient reports and a Logistic Regression classifier to predict whether a medication is causing a negative side effect.

## What the Code Did

1. **Data Preparation:** It defined a list of 6 patient reports (some describing side effects, others describing positive outcomes) and assigned binary labels (1 for ADR present, 0 for No ADR).
2. **Tokenization:** It used the `BertTokenizer` to convert raw text into numerical IDs that the BERT model can process.
3. **Embedding Generation:** It passed the tokenized text through the bert-base-uncased model. It extracted the vector representation (embedding) of the special [CLS] token, which represents the entire document's semantic meaning.
4. **Training and Prediction:** It trained a Logistic Regression classifier on these embeddings to distinguish between "ADR" and "No ADR" classes. It then used this classifier to predict the class for the input reports.

## What the Output Means

**Tokenization Output:** The output shows how BERT handles sub-word tokenization (WordPiece). For example, the drug name "metformin" was split into met, ##form, and ##in.

**Detection Results:** The model assigned high confidence scores (e.g., 93-96%) to reports describing negative symptoms (like nausea, rash, insomnia), while assigning very low scores (e.g., 5-6%) to reports describing positive outcomes.

**Classification Report:** The metrics (Precision, Recall, F1-score) are all 1.00. This indicates that the model achieved 100% accuracy on this specific small dataset, correctly classifying every single example.

# **Electronic Submission**

When you run the code in the cell below, it will grade your Colab notebook and tell you your pending grade as it currently stands. You will be given the choice to either submit your notebook for final grading or the option to continue your work on one (or more) Exercises. You no longer have the option to upload a PDF of your Colab notebook to Canvas for grading. Grant Access to your Colab Secrets if you are asked to do so. (3) having to resubmit to Canvas so they can grade it

In [ ]:
# @title Electronic Submission

import urllib.request
import ssl
import time

url = "https://biologicslab.co/BIO1173/backend_code/validate.py?v=" + str(time.time())

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

req = urllib.request.Request(
    url,
    headers={
        "Cache-Control": "no-cache, no-store, must-revalidate",
        "Pragma": "no-cache",
        "Expires": "0"
    }
)

with urllib.request.urlopen(req, context=ctx) as r:
    exec(r.read().decode("utf-8"))

main()